# Generated by Django 4.2.7 on 2023-11-07 21:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Coins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999)])),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=64)),
                ('nItem', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999)])),
                ('itemdescription', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('itempicture', models.ImageField(upload_to='item_pictures/')),
            ],
        ),
    ]
