# Generated by Django 4.2.7 on 2023-11-26 14:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swapmarket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coins',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coins', to='swapmarket.item'),
        ),
        migrations.AddField(
            model_name='coins',
            name='nItem',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
    ]
