# Generated by Django 4.2.7 on 2023-11-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapmarket', '0002_coins_receiver_coins_sender_item_buyers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itempicture',
            field=models.ImageField(upload_to='item_pictures/'),
        ),
    ]
