# Generated by Django 4.2.7 on 2023-11-17 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swapmarket', '0003_item_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='tags',
            new_name='itemtag',
        ),
    ]
