# Generated by Django 4.2.7 on 2023-11-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapmarket', '0004_rename_tags_item_itemtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='payment',
            field=models.CharField(blank=True, choices=[('coin', 'Coin'), ('other', 'Other')], max_length=64, null=True),
        ),
    ]
