# Generated by Django 4.2.7 on 2023-11-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapmarket', '0005_item_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemname',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
