# Generated by Django 4.2.7 on 2023-11-09 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='displayname',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
