# Generated by Django 4.2.7 on 2023-11-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_customuser_displayname_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='displayname',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
